//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gear.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gear.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedendum Clearance.
        /// </summary>
        internal static string AddDedendumClearance {
            get {
                return ResourceManager.GetString("AddDedendumClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment Plane.
        /// </summary>
        internal static string AlignmentPlaneBodyName {
            get {
                return ResourceManager.GetString("AlignmentPlaneBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Alignment.
        /// </summary>
        internal static string AlignmentPlaneLayerName {
            get {
                return ResourceManager.GetString("AlignmentPlaneLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Alignment Planes.
        /// </summary>
        internal static string AlignmentPlanePartName {
            get {
                return ResourceManager.GetString("AlignmentPlanePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string BevelAngleText {
            get {
                return ResourceManager.GetString("BevelAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knee Ratio.
        /// </summary>
        internal static string BevelKneeRatioText {
            get {
                return ResourceManager.GetString("BevelKneeRatioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular Pitch: {0:0.000}, Center Distance: {1:0.000}, Overall Width: {2:0.000}.
        /// </summary>
        internal static string CalculationsLine1Text {
            get {
                return ResourceManager.GetString("CalculationsLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Gear Diameters: Pitch: {0:0.000}, Addendum: {1:0.000}, Dedendum: {2:0.000}.
        /// </summary>
        internal static string CalculationsLine2Text {
            get {
                return ResourceManager.GetString("CalculationsLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Gear Diameters: Pitch: {0:0.000}, Addendum: {1:0.000}, Dedendum: {2:0.000}.
        /// </summary>
        internal static string CalculationsLine3Text {
            get {
                return ResourceManager.GetString("CalculationsLine3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a gear pair..
        /// </summary>
        internal static string CreateGearCommandHint {
            get {
                return ResourceManager.GetString("CreateGearCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateGearCommandText {
            get {
                return ResourceManager.GetString("CreateGearCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string CreateGroupText {
            get {
                return ResourceManager.GetString("CreateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedendum Clearance.
        /// </summary>
        internal static string DedendumClearanceText {
            get {
                return ResourceManager.GetString("DedendumClearanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        internal static string DepthText {
            get {
                return ResourceManager.GetString("DepthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: gear parameters result in invalid profile.  Please see curves..
        /// </summary>
        internal static string ErrorInvalidGearProfile {
            get {
                return ResourceManager.GetString("ErrorInvalidGearProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fillet Radius.
        /// </summary>
        internal static string FilletRadiusText {
            get {
                return ResourceManager.GetString("FilletRadiusText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations.
        /// </summary>
        internal static string GearCalculationsGroupText {
            get {
                return ResourceManager.GetString("GearCalculationsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        internal static string GearLayerName {
            get {
                return ResourceManager.GetString("GearLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Alignment Circles.
        /// </summary>
        internal static string GearMountAlignmentCircleLayer {
            get {
                return ResourceManager.GetString("GearMountAlignmentCircleLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Mount {0}-{1}.
        /// </summary>
        internal static string GearMountPartName {
            get {
                return ResourceManager.GetString("GearMountPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string GearNameSimple {
            get {
                return ResourceManager.GetString("GearNameSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear: {2} teeth, {3:0.0}°, {0:0.00}{1} module.
        /// </summary>
        internal static string GearPartNameFormat {
            get {
                return ResourceManager.GetString("GearPartNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string HelicalAngleText {
            get {
                return ResourceManager.GetString("HelicalAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string HypoidAngleText {
            get {
                return ResourceManager.GetString("HypoidAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string HypoidOffsetText {
            get {
                return ResourceManager.GetString("HypoidOffsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevel.
        /// </summary>
        internal static string IsBevelText {
            get {
                return ResourceManager.GetString("IsBevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helical.
        /// </summary>
        internal static string IsHelicalText {
            get {
                return ResourceManager.GetString("IsHelicalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypoid.
        /// </summary>
        internal static string IsHypoidText {
            get {
                return ResourceManager.GetString("IsHypoidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screw.
        /// </summary>
        internal static string IsScrewText {
            get {
                return ResourceManager.GetString("IsScrewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string ModuleText {
            get {
                return ResourceManager.GetString("ModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Body {0}.
        /// </summary>
        internal static string MountBodyName {
            get {
                return ResourceManager.GetString("MountBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Gear Teeth.
        /// </summary>
        internal static string NumberOfTeethLText {
            get {
                return ResourceManager.GetString("NumberOfTeethLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Gear Teeth.
        /// </summary>
        internal static string NumberOfTeethRText {
            get {
                return ResourceManager.GetString("NumberOfTeethRText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Pitch Circles.
        /// </summary>
        internal static string PitchCircleLayerName {
            get {
                return ResourceManager.GetString("PitchCircleLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        internal static string PitchCircleSurfaceName {
            get {
                return ResourceManager.GetString("PitchCircleSurfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Angle.
        /// </summary>
        internal static string PressureAngleText {
            get {
                return ResourceManager.GetString("PressureAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias.
        /// </summary>
        internal static string ScrewAngleBiasText {
            get {
                return ResourceManager.GetString("ScrewAngleBiasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string ScrewAngleText {
            get {
                return ResourceManager.GetString("ScrewAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string TabText {
            get {
                return ResourceManager.GetString("TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trochoidal Interference Removal.
        /// </summary>
        internal static string UseTrochoidalText {
            get {
                return ResourceManager.GetString("UseTrochoidalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        internal static string VisualizationBodyLayerName {
            get {
                return ResourceManager.GetString("VisualizationBodyLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch Surface.
        /// </summary>
        internal static string VisualizationBodyName {
            get {
                return ResourceManager.GetString("VisualizationBodyName", resourceCulture);
            }
        }
    }
}
