//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string ApiGrooveGroupText {
            get {
                return ResourceManager.GetString("ApiGrooveGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a circular edge to create an API Groove..
        /// </summary>
        internal static string ApiGrooveStatusText {
            get {
                return ResourceManager.GetString("ApiGrooveStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an API groove of a desired size..
        /// </summary>
        internal static string ApiGrooveToolHint {
            get {
                return ResourceManager.GetString("ApiGrooveToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///  &lt;panel&gt;
        ///    &lt;group id=&quot;ApiGrooveToolGroup&quot; label=&quot;API Groove&quot;&gt;
        ///      &lt;container id=&quot;ApiGrooveToolContainerSize&quot; layoutOrientation=&quot;horizontal&quot;&gt;
        ///        &lt;label id=&quot;ApiGrooveToolSizeLabel&quot; text=&quot;Size:&quot; width=&quot;40&quot;/&gt;
        ///        &lt;comboBox id=&quot;ApiGrooveToolSizeList&quot; command=&quot;ApiGrooveToolSizeList&quot; textEditable=&quot;false&quot; type=&quot;default&quot; width=&quot;130&quot; /&gt;
        ///      &lt;/container&gt;
        ///    &lt;/group&gt;
        ///  &lt;/panel&gt;
        ///&lt;/customUI&gt;.
        /// </summary>
        internal static string ApiGrooveToolOptions {
            get {
                return ResourceManager.GetString("ApiGrooveToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Groove.
        /// </summary>
        internal static string ApiGrooveToolText {
            get {
                return ResourceManager.GetString("ApiGrooveToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create threads on selected cylinder..
        /// </summary>
        internal static string CreateThreadsCommandHint {
            get {
                return ResourceManager.GetString("CreateThreadsCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateThreadsCommandText {
            get {
                return ResourceManager.GetString("CreateThreadsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute.
        /// </summary>
        internal static string DistributeGroupText {
            get {
                return ResourceManager.GetString("DistributeGroupText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DistributeSpheres32 {
            get {
                object obj = ResourceManager.GetObject("DistributeSpheres32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute spheres across a body using a physics-based partical model..
        /// </summary>
        internal static string DistributeSpheresCommandHint {
            get {
                return ResourceManager.GetString("DistributeSpheresCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spheres.
        /// </summary>
        internal static string DistributeSpheresCommandText {
            get {
                return ResourceManager.GetString("DistributeSpheresCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string DistributeSpheresToolAnimationPause {
            get {
                return ResourceManager.GetString("DistributeSpheresToolAnimationPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string DistributeSpheresToolAnimationPlay {
            get {
                return ResourceManager.GetString("DistributeSpheresToolAnimationPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string DistributeSpheresToolAnimationStep {
            get {
                return ResourceManager.GetString("DistributeSpheresToolAnimationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evenly distribute spheres on a face..
        /// </summary>
        internal static string DistributeSpheresToolHint {
            get {
                return ResourceManager.GetString("DistributeSpheresToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///	&lt;panel&gt;
        ///		&lt;group id=&quot;DistributeSpheresToolGroup&quot; label=&quot;Profile Options&quot;&gt;
        ///			&lt;container id=&quot;DistributeSpheresToolContainer&quot; layoutOrientation=&quot;vertical&quot;&gt;
        ///				&lt;container id=&quot;DistributeSpheresToolContainerColor&quot; layoutOrientation=&quot;horizontal&quot;&gt;
        ///					&lt;label id=&quot;DistributeSpheresToolColorLabel&quot; text=&quot;Color:&quot; width=&quot;40&quot;/&gt;
        ///
        ///					&lt;!--
        ///						Combo box items can either be specified in XML, or specified by setti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DistributeSpheresToolOptions {
            get {
                return ResourceManager.GetString("DistributeSpheresToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Spheres.
        /// </summary>
        internal static string DistributeSpheresToolText {
            get {
                return ResourceManager.GetString("DistributeSpheresToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        internal static string IsImperial {
            get {
                return ResourceManager.GetString("IsImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string IsInternal {
            get {
                return ResourceManager.GetString("IsInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        internal static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Threads32 {
            get {
                object obj = ResourceManager.GetObject("Threads32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        internal static string ThreadsGroupText {
            get {
                return ResourceManager.GetString("ThreadsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        internal static string ThreadStructureText {
            get {
                return ResourceManager.GetString("ThreadStructureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string UtilitiesText {
            get {
                return ResourceManager.GetString("UtilitiesText", resourceCulture);
            }
        }
    }
}
