//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unfold.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unfold.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string AnnotationLayerName {
            get {
                return ResourceManager.GetString("AnnotationLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane.
        /// </summary>
        internal static string AnnotationPlaneName {
            get {
                return ResourceManager.GetString("AnnotationPlaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Planes.
        /// </summary>
        internal static string AnnotationPlanesLayerName {
            get {
                return ResourceManager.GetString("AnnotationPlanesLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Size.
        /// </summary>
        internal static string BreakLinesDashSize {
            get {
                return ResourceManager.GetString("BreakLinesDashSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Lines.
        /// </summary>
        internal static string BreakLinesLayerName {
            get {
                return ResourceManager.GetString("BreakLinesLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Angle.
        /// </summary>
        internal static string BreakLinesMinimumAngle {
            get {
                return ResourceManager.GetString("BreakLinesMinimumAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates curve copies of the edges of selected faces, removing duplicate edges..
        /// </summary>
        internal static string CopyCurvesHint {
            get {
                return ResourceManager.GetString("CopyCurvesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Curves.
        /// </summary>
        internal static string CopyCurvesText {
            get {
                return ResourceManager.GetString("CopyCurvesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forget what this does..
        /// </summary>
        internal static string CreateAnimateCommandHint {
            get {
                return ResourceManager.GetString("CreateAnimateCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string CreateAnimateCommandText {
            get {
                return ResourceManager.GetString("CreateAnimateCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dashes.
        /// </summary>
        internal static string CreateDashesText {
            get {
                return ResourceManager.GetString("CreateDashesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateGroupText {
            get {
                return ResourceManager.GetString("CreateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a dashed chain along a chain of curve segments.  Curves must be a well connected chain..
        /// </summary>
        internal static string DashChainHint {
            get {
                return ResourceManager.GetString("DashChainHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Chain.
        /// </summary>
        internal static string DashChainText {
            get {
                return ResourceManager.GetString("DashChainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashes.
        /// </summary>
        internal static string DashesGroupText {
            get {
                return ResourceManager.GetString("DashesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a dashed line with evenly spaced segments at least as big as the minimum size..
        /// </summary>
        internal static string DashesHint {
            get {
                return ResourceManager.GetString("DashesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashes.
        /// </summary>
        internal static string DashesText {
            get {
                return ResourceManager.GetString("DashesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Size.
        /// </summary>
        internal static string DashSizeText {
            get {
                return ResourceManager.GetString("DashSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Collisions.
        /// </summary>
        internal static string DetectCollisionsText {
            get {
                return ResourceManager.GetString("DetectCollisionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting Lines.
        /// </summary>
        internal static string FlatCuttingLinesLayerName {
            get {
                return ResourceManager.GetString("FlatCuttingLinesLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Bodies.
        /// </summary>
        internal static string FlatFaceLayerName {
            get {
                return ResourceManager.GetString("FlatFaceLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Face.
        /// </summary>
        internal static string FlatFaceName {
            get {
                return ResourceManager.GetString("FlatFaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Engraving.
        /// </summary>
        internal static string FlatMediumEngravingLayerName {
            get {
                return ResourceManager.GetString("FlatMediumEngravingLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Pattern.
        /// </summary>
        internal static string FlatPatternText {
            get {
                return ResourceManager.GetString("FlatPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curves on Breaks.
        /// </summary>
        internal static string IsCreatingBreakLines {
            get {
                return ResourceManager.GetString("IsCreatingBreakLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold.
        /// </summary>
        internal static string TabText {
            get {
                return ResourceManager.GetString("TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular Deviation.
        /// </summary>
        internal static string TesselateAngleDeviationText {
            get {
                return ResourceManager.GetString("TesselateAngleDeviationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Deviation.
        /// </summary>
        internal static string TesselateSurfaceDeviationText {
            get {
                return ResourceManager.GetString("TesselateSurfaceDeviationText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tessellate {
            get {
                object obj = ResourceManager.GetObject("Tessellate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a body from the current body&apos;s current visible tessellation..
        /// </summary>
        internal static string TessellateCommandHint {
            get {
                return ResourceManager.GetString("TessellateCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tessellate Body.
        /// </summary>
        internal static string TessellateCommandText {
            get {
                return ResourceManager.GetString("TessellateCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses three or more curves to generate a foldable cone with creases on those curves..
        /// </summary>
        internal static string TessellateFoldCornerCommandHint {
            get {
                return ResourceManager.GetString("TessellateFoldCornerCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold Corner.
        /// </summary>
        internal static string TessellateFoldCornerCommandText {
            get {
                return ResourceManager.GetString("TessellateFoldCornerCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tessellate.
        /// </summary>
        internal static string TessellateGroupText {
            get {
                return ResourceManager.GetString("TessellateGroupText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TessellateLoft {
            get {
                object obj = ResourceManager.GetObject("TessellateLoft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tessellated Loft.
        /// </summary>
        internal static string TessellateLoftBodyName {
            get {
                return ResourceManager.GetString("TessellateLoftBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a tessellated loft between two curves..
        /// </summary>
        internal static string TessellateLoftCommandHint {
            get {
                return ResourceManager.GetString("TessellateLoftCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loft.
        /// </summary>
        internal static string TessellateLoftCommandText {
            get {
                return ResourceManager.GetString("TessellateLoftCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Size.
        /// </summary>
        internal static string TessellateLoftStepSize {
            get {
                return ResourceManager.GetString("TessellateLoftStepSize", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Unfold {
            get {
                object obj = ResourceManager.GetObject("Unfold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When unfolding, see if the unfolded faces interfere with each other and seek alternate solutions..
        /// </summary>
        internal static string UnfoldCollisionDetectionCommandHint {
            get {
                return ResourceManager.GetString("UnfoldCollisionDetectionCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Collisions.
        /// </summary>
        internal static string UnfoldCollisionDetectionCommandText {
            get {
                return ResourceManager.GetString("UnfoldCollisionDetectionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfolds the selected body to a flat pattern..
        /// </summary>
        internal static string UnfoldCommandHint {
            get {
                return ResourceManager.GetString("UnfoldCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold Body.
        /// </summary>
        internal static string UnfoldCommandText {
            get {
                return ResourceManager.GetString("UnfoldCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tabs for easier taping or glueing..
        /// </summary>
        internal static string UnfoldCreateTabsCommandHint {
            get {
                return ResourceManager.GetString("UnfoldCreateTabsCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tabs.
        /// </summary>
        internal static string UnfoldCreateTabsCommandText {
            get {
                return ResourceManager.GetString("UnfoldCreateTabsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold.
        /// </summary>
        internal static string UnfoldGroupText {
            get {
                return ResourceManager.GetString("UnfoldGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: not all faces of the body are planes. Problematic faces are now colored red.  Consider using the Tessellate command to convert the geometry..
        /// </summary>
        internal static string UnfoldNotPlanarError {
            get {
                return ResourceManager.GetString("UnfoldNotPlanarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that all of the faces of the selected body are planar..
        /// </summary>
        internal static string UnfoldVerifyPlanarCommandHint {
            get {
                return ResourceManager.GetString("UnfoldVerifyPlanarCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Planar.
        /// </summary>
        internal static string UnfoldVerifyPlanarCommandText {
            get {
                return ResourceManager.GetString("UnfoldVerifyPlanarCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold bodies in all components and include any curves cooinciden with the faces..
        /// </summary>
        internal static string UnfoldWithCurvesCommandHint {
            get {
                return ResourceManager.GetString("UnfoldWithCurvesCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts with Curves.
        /// </summary>
        internal static string UnfoldWithCurvesCommanText {
            get {
                return ResourceManager.GetString("UnfoldWithCurvesCommanText", resourceCulture);
            }
        }
    }
}
